### ISSUE TITLE
Not working on GCP (gke) due to auth provider error

### ISSUE THREAD

**Issue by agolomoodysaada** [gabeduke/kubectl-iexec#14]
Not working on GCP due to this error after running

```
$ k iexec <mypod> bash
FATA[0000] No Auth Provider found for name "gcp"
```

**Comment by gabeduke** [comment]
thanks for finding this @agolomoodysaada ! Can you try the latest version it should be fixed now.

**Comment by agolomoodysaada** [comment]
worked like a charm! thanks
