### ISSUE TITLE
kubectl-ilog?

### ISSUE THREAD

**Issue by andsens** [gabeduke/kubectl-iexec#44]
I love `iexec`, it has helped me countless times to just get stuff done when debugging / building my cluster. Is there any chance you could be convinced to create something similar for `kubectl log`?
I have log aggregation and everything else up and running, but sometimes it's just quicker to get the data directly from the cli. I think something like `ilog` could help significantly in that respect.

The ultimate plugin would be a `kubectl` command wrapper where you do the fuzzy lookup for all entities and all commands, which obviously is a bit of a bigger challenge.
e.g. `kubectl i get sts -o yaml prom` would search for stateful sets matching `prom` and show a selection if there is any ambiguity before forwarding the command.

**Comment by rafaelgaspar** [comment]
Have you looked into https://github.com/wercker/stern?

**Comment by gabeduke** [comment]
thanks @andsens great to hear you like the plugin! I use [stern](https://github.com/wercker/stern) as well. I would not be able to build a better tool on my own.

**Comment by andsens** [comment]
Oh boy! I have not, thank you for the link. Seems to be exactly what I'm looking for!
