### ISSUE TITLE
By default use the namespace configured in Kubernetes context

### ISSUE THREAD

**Issue by ananthakumaran** [gabeduke/kubectl-iexec#46]
Thanks for writing the plugin. Currently, it works for me if I explicitly provide the namespace, otherwise, it just hangs. From the logs, it looks like the plugin is trying to fetch pod list info from all the namespaces which can be quite big and slow.

```
Flags:
      --all-namespaces             If present, tail across all namespaces. A specific namespace is ignored even if specified with --namespace.
  -n, --namespace string           Kubernetes namespace to use. Default to namespace configured in Kubernetes context
```

[stern](https://github.com/wercker/stern) has the above options, which plays nicely with large k8s cluster.

**Comment by gabeduke** [comment]
Thanks for reporting this @ananthakumaran I'll try and get this fixed!

**Comment by gabeduke** [comment]
This is fixed on the master branch but I am going to fix CI and get a release published.

**Comment by gabeduke** [comment]
@ananthakumaran the newest release (v1.6.2) should fix this issue for you. Let me know if you have any issues!

**Comment by ananthakumaran** [comment]
@gabeduke Thanks for the quick fix. Verified and works as expected.
