### ISSUE TITLE
Arm64 Support

### ISSUE THREAD

**Issue by jarojasm95** [gabeduke/kubectl-iexec#56]
Trying to install on an Apple M1 chip and getting:

`failed to install plugin "iexec": plugin "iexec" does not offer installation for this platform`

**Comment by jarojasm95** [comment]
I am able to use the plugin for now by having manually run `go build` from source

**Comment by gabeduke** [comment]
@jarojasm95 great call out I'll fix this asap 🙂

**Comment by gabeduke** [comment]
Once this PR is merged you should be able to test pulling the arm binary via krew.

https://github.com/kubernetes-sigs/krew-index/pull/1543
