### ISSUE TITLE
subshell terminal not using parent's width

### ISSUE THREAD

**Issue by gabeduke** [gabeduke/kubectl-iexec#6]
Subshell is breaking long text strings because it is using a different width than the original terminal

**Comment by gabeduke** [comment]
Unable to reproduce

**Comment by soundmonster** [comment]
I can confirm that this issue affects my setup. Macos 10.14.6, iTerm2 3.3.7, tmux 2.9a, zsh 5.7.1, ncurses 6.1, and
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gabeduke** [comment]
@soundmonster thanks for the info I knew this was an issue but not how to recreate this is super helpful 😀

Let me try to replicate on my end I suspect it is related to tmux spawning a subshell.
