### ISSUE TITLE
revise the error message in case no running pods found

### ISSUE THREAD

**Issue by Dentrax** [gabeduke/kubectl-iexec#66]
What I expect here is that something like `no running pods found`. We are already checking the `err` case, but not `len(pods) == 0` [in here](https://github.com/gabeduke/kubectl-iexec/blob/101805077b04d4f834929b1c0b36768d2b30b501/pkg/iexec/kubernetes.go#L18-L21).

**Actual:**
```bash
$ k get pods
NAME         READY   STATUS             RESTARTS   AGE
foo-1        0/1     ImagePullBackOff   0          15h
foo-2        0/1     ImagePullBackOff   0          26h
foo-3        0/1     ImagePullBackOff   0          175m

$ kubectl iexec foo --log-level trace
DEBU[0000] iexec config values...                        Naked=false Namespace=test Vim Mode=false containerFilter= podFilter=foo remote command="[/bin/sh]"
DEBU[0000] total pods discovered...                      namespace=test pods=0
INFO[0000] Get all pods for podFilter...                 SearchFilter=foo
FATA[0000] no pods found for filter: foo
```

**Expected:**
```bash
$ kubectl iexec foo
no running pods found
```

cc: @eminaktas

**Comment by eminaktas** [comment]
With the new commit, it will look like the first attempt within the screenshot.

<img width="348" alt="Screen Shot 2021-11-09 at 11 43 54" src="https://user-images.githubusercontent.com/54074230/140891429-ce1203f6-3f50-472d-a385-996f1e9c120d.png">

cc: @Dentrax
